#!/bin/bash

# If for whatever reason you're not using /root, change this.
cp -f profile/* /home/root

# Update things before we install things
apt update && apt dist-upgrade && apt autoremove

# Let's install lots of packages
apt install \
  kali-tools-802-11 \
  kali-tools-bluetooth \
  kali-tools-crypto-stego \
  kali-tools-database \
  kali-tools-exploitation \
  kali-tools-forensics \
  kali-tools-fuzzing \
  kali-tools-gpu \
  kali-tools-hardware \
  kali-tools-headless \
  kali-tools-information-gathering \
  kali-tools-passwords \
  kali-tools-post-exploitation \
  kali-tools-reporting \
  kali-tools-reverse-engineering \
  kali-tools-rfid \
  kali-tools-sdr \
  kali-tools-sniffing-spoofing \
  kali-tools-social-engineering \
  kali-tools-top10 \
  kali-tools-voip \
  kali-tools-vulnerability \
  kali-tools-web \
  kali-tools-windows-resources \
  kali-tools-wireless \
  gdm3 mate \
  chromium tor tor-browser \
  crackmapexec \
  powershell powershell-empire powersploit \
  neo4j bloodhound \
  testssl sslscan \
  postgresql \
  vim

# Initialize Metasploit database
msfdb --init

# Grab some things from Github
cd /opt
git clone https://github.com/hak5darren/USB-Rubber-Ducky.git
git clone https://github.com/dbcli/mssql-cli
