#!/bin/bash

# If for whatever reason you're not using /root, change this.
echo ' '
echo '========================'
echo 'Copying profile files...'
echo '========================'
echo ' '
cp -f profile/* ~

# Update things before we install things
echo '================'
echo 'Updating Kali...'
echo '================'
echo ' '
apt update && apt dist-upgrade && apt autoremove

# Let's install lots of packages
echo '=========================================='
echo 'Installing useful things from Kali repo...'
echo '=========================================='
echo ' '
apt install \
  kali-tools-802-11 \
  kali-tools-bluetooth \
  kali-tools-crypto-stego \
  kali-tools-database \
  kali-tools-exploitation \
  kali-tools-forensics \
  kali-tools-fuzzing \
  kali-tools-gpu \
  kali-tools-hardware \
  kali-tools-headless \
  kali-tools-information-gathering \
  kali-tools-passwords \
  kali-tools-post-exploitation \
  kali-tools-reporting \
  kali-tools-reverse-engineering \
  kali-tools-rfid \
  kali-tools-sdr \
  kali-tools-sniffing-spoofing \
  kali-tools-social-engineering \
  kali-tools-top10 \
  kali-tools-voip \
  kali-tools-vulnerability \
  kali-tools-web \
  kali-tools-windows-resources \
  kali-tools-wireless \
  gdm3 cinnamon \
  chromium tor torbrowser-launcher \
  crackmapexec \
  powershell powershell-empire powersploit \
  neo4j bloodhound \
  jython jruby testssl.sh sslscan \
  python3-pip \
  postgresql \
  vim gedit \
  wireguard
apt autoremove

# Initialize Metasploit database
echo '==================================='
echo 'Initializing Metasploit database...'
echo '==================================='
echo ' '
systemctl start postgresql.service
msfdb init

# Grab some things from Github
echo '======================================'
echo 'Installing extra Python-based tools...'
echo '======================================'
echo ' '
python3 -m pip install mssql-cli

# Grab some things from Github
echo '================================'
echo 'Installing extras from Github...'
echo '================================'
echo ' '
cd /opt
git clone https://github.com/hak5darren/USB-Rubber-Ducky.git

# Configure desktop display
# Grab some things from Github
echo '================================'
echo 'Configuring desktop...'
echo '================================'
echo ' '
echo "cinnamon" > ~/.xsession
# Note: Make sure 3D hardware accelleration is turned on in the VM hardware
# settings. If it is and you still get a pop-up that it's not working or you
# get rendering errors, uncomment and run the following.
# echo "cinnamon-session-cinnamon2d" > ~/.xsession
# TODO: Add resolution options
